# Xiaomi Air Purifier 2S
- alias: Air Purifier mode change
  trigger:
    entity_id: input_select.xiaomi_airpurifier_mode
    platform: state
  action:
    service: fan.set_speed
    data_template:
      entity_id: fan.xiaomi_miio_device
      speed: '{{ states.input_select.xiaomi_airpurifier_mode.state }}'
- alias: Air Purifier mode changed
  trigger:
    platform: state
    entity_id: fan.xiaomi_miio_device
  action:
    service: input_select.select_option
    entity_id: input_select.xiaomi_airpurifier_mode
    data_template:
      option: '{{ states.fan.xiaomi_miio_device.attributes.speed }}'
- alias: Air Purifier favorite level change
  trigger:
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    platform: state
  action:
    service: xiaomi_miio.fan_set_favorite_level
    data_template:
      entity_id: fan.xiaomi_miio_device
      level: '{{ states.input_number.xiaomi_airpurifier_favorite_level.state | int }}'
- alias: Air Purifier favorite level changed
  trigger:
    platform: state
    entity_id: fan.xiaomi_miio_device
  action:
    service: input_number.set_value
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    data_template:
      value: '{{ states.fan.xiaomi_miio_device.attributes.favorite_level }}'
      
      
# Автовыключение
- alias: air_putifier_auto_off
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.xiaomi_airpurifier_air_quality_pm25
      below: 2
  condition:
    - condition: state
      entity_id: fan.xiaomi_miio_device
      state: 'on'
  action:
    - service: system_log.write
      data_template:
        level: info
        logger: my_info
        message: "Air is good!!"
    - service: system_log.write
      data:
        message: "Air is good!"
        level: info
    - service: homeassistant.turn_off
      entity_id: fan.xiaomi_miio_device
      
# Автовключение
- alias: air_putifier_auto_on
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.xiaomi_airpurifier_air_quality_pm25
      above: 5
  condition:
    - condition: state
      entity_id: fan.xiaomi_miio_device
      state: 'off'
  action:
    - service: system_log.write
      data_template:
        level: info
        logger: my_info
        message: "Air is bad!!"
    - service: system_log.write
      data:
        message: "Air is bad!"
        level: warn
    - service: homeassistant.turn_on
      entity_id: fan.xiaomi_miio_device