# Xiaomi Air Purifier 2S
- alias: Air Purifier mode change
  trigger:
    entity_id: input_select.xiaomi_airpurifier_mode
    platform: state
  action:
    - service: fan.set_preset_mode
      target:
        entity_id: fan.air_purifier
      data:
        preset_mode: '{{ states.input_select.xiaomi_airpurifier_mode.state }}'
        
- alias: Air Purifier mode changed
  trigger:
    platform: state
    entity_id: fan.air_purifier
  condition:
    alias: "airpurifier preset_mode is not Unknown"
    condition: not
    conditions:
        - condition: state
          entity_id: sensor.xiaomi_airpurifier_preset_mode
          state: "unknown"
  action:
    service: input_select.select_option
    entity_id: input_select.xiaomi_airpurifier_mode
    data_template:
      option: '{{ states.fan.air_purifier.attributes.preset_mode }}'
      
- alias: Air Purifier favorite level change
  trigger:
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    platform: state
  action:
    service: number.set_value
    data_template:
      entity_id: number.air_purifier_favorite_level
      value: '{{ states.input_number.xiaomi_airpurifier_favorite_level.state | int }}'
      
- alias: Air Purifier favorite level changed
  trigger:
    platform: state
    entity_id: number.air_purifier_favorite_level
  condition:
    alias: "airpurifier favorite_level is not Unknown"
    condition: not
    conditions:
        - condition: state
          entity_id: number.air_purifier_favorite_level
          state: "unknown"
  action:
    service: input_number.set_value
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    data_template:
      value: '{{ states.number.air_purifier_favorite_level.state | int  }}'
      
      
# Автовыключение
- alias: air_putifier_auto_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: fan.air_purifier
    - platform: state
      entity_id: sensor.air_purifier_pm2_5
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: fan.air_purifier
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.air_purifier_pm2_5
          below: 2
  action:
    - service: system_log.write
      data_template:
        level: info
        logger: automation_air-purifier-2s
        message: "Air is good!!"
    - service: fan.set_preset_mode
      target:
        entity_id: fan.air_purifier
      data:
        preset_mode: 'Auto'
    - service: homeassistant.turn_off
      entity_id: fan.air_purifier
      
# Автовключение
- alias: air_putifier_auto_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: fan.air_purifier
    - platform: state
      entity_id: sensor.air_purifier_pm2_5
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: fan.air_purifier
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.air_purifier_pm2_5
          above: 5
  action:
    - service: system_log.write
      data_template:
        level: info
        logger: automation_air-purifier-2s
        message: "Air is bad!!"
    - service: homeassistant.turn_on
      entity_id: fan.air_purifier
      
      
      