# Не спать!
- alias: tv_auto_wol
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.philips_wol
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: switch.philips_wol
          state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.philips_wol
    - service: switch.turn_on
      entity_id: switch.philips_wol


# Автовключение
- alias: speakers_volume_auto_on
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x4cf8cdf3c764d02_power
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.philips_tv_screen
          state: "on"
        - condition: state
          entity_id: switch.sven_volume
          state: "off"
  action:
    - service: system_log.write
      data_template:
        level: info
        logger: automation_sven_volume_auto
        message: "TV Screen is ON now!"
    - service: switch.turn_on
      entity_id: switch.sven_volume
    # - service: script.call_sven_vol_up_32

# Автовыключение
- alias: speakers_volume_auto_off
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x4cf8cdf3c764d02_power
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.philips_tv_screen
          state: "off"
        - condition: state
          entity_id: switch.sven_volume
          state: "on"
  action:
    - service: system_log.write
      data_template:
        level: info
        logger: automation_sven_volume_auto
        message: "TV screen is OFF now!"
    - service: switch.turn_off
      entity_id: switch.sven_volume
    # - service: script.call_sven_vol_down_32      