- alias: "Turn on wardrobe light when there is movement"
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d00054cd813_occupancy
    to: "on"
  action:
  - service: timer.cancel
    target:
        entity_id: timer.wardrobe_light
  - service: light.turn_on
    target:
      entity_id: light.0x00158d00052b3ad9

- alias: "Turn off wardrobe light 1 minute after last movement"
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d00054cd813_occupancy
    to: "off"
    for:
      seconds: 5
  action:
    service: light.turn_off
    target:
      entity_id: light.0x00158d00052b3ad9
      
- alias: "Start timer if light turned on manually"
  trigger: 
  - platform: state
    entity_id: light.0x00158d00052b3ad9
    to: "on"
  condition:
    condition: state
    entity_id: binary_sensor.0x00158d00054cd813_occupancy
    state: "off"
  action:
  - service: timer.cancel
    target:
        entity_id: timer.wardrobe_light
  - service: timer.start
    target:
        entity_id: timer.wardrobe_light
        
- alias: "Cancel timer if light turned off"
  trigger: 
  - platform: state
    entity_id: light.0x00158d00052b3ad9
    to: "off"
  action:
  - service: timer.cancel
    target:
        entity_id: timer.wardrobe_light

- alias: "Turn off light when timer finished"
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wardrobe_light
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.0x00158d00052b3ad9
      

- alias: "Make light darker after sunset"
  trigger:
  - platform: state
    entity_id: light.0x00158d00052b3ad9
    to: "on"
  condition:
    condition: state
    entity_id: sun.sun
    state: "below_horizon"
  action:
    service: light.turn_on
    target:
      entity_id: light.0x00158d00052b3ad9
    data:
      brightness_pct: 20
      color_temp: 500

- alias: "Make light lighter after sunrise"
  trigger:
  - platform: state
    entity_id: light.0x00158d00052b3ad9
    to: "on"
  condition:
    condition: state
    entity_id: sun.sun
    state: "above_horizon"
  action:
    service: light.turn_on
    target:
      entity_id: light.0x00158d00052b3ad9
    data:
      brightness_pct: 80
      color_temp: 153

    