- alias: "Turn on wardrobe light when there is movement"
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d00054cd813_motion
    to: "on"
  action:
  - service: timer.cancel
    target:
        entity_id: timer.wardrobe_light
  - service: timer.start
    target:
        entity_id: timer.wardrobe_light
  - service: light.turn_on
    target:
      entity_id: light.0x158d00052b3ad9_light

- alias: "Turn off wardrobe light 1 minute after last movement"
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d00054cd813_motion
    to: "off"
    for:
      seconds: 5
  action:
    service: light.turn_off
    target:
      entity_id: light.0x158d00052b3ad9_light