# Автовыключение
- alias: sven_volume_auto_off
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.android_tv
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.android_tv
          state: 'off'
  action:
    - service: system_log.write
      data_template:
        level: info
        logger: automation_sven_volume_auto_off
        message: "Philips TV is Off now!"
    - service: switch.turn_off
      entity_id: switch.sven_volume
    # - service: script.call_sven_vol_down_32
      
# Автовключение
- alias: sven_volume_auto_on
  initial_state: true
  trigger:
    platform: state
    entity_id: media_player.android_tv
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.android_tv
          state: 'on'
  action:
    - service: system_log.write
      data_template:
        level: info
        logger: automation_sven_volume_auto_off
        message: "Philips TV is On now!"
    - service: switch.turn_on
      entity_id: switch.sven_volume
    # - service: script.call_sven_vol_up_32
      