homeassistant:
  name: Moskvorech'e
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 130
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages
  
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
    mode: yaml
    resources:    
      - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
        type: module
      - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
        type: module
      - url: /hacsfiles/vacuum-card/vacuum-card.js
        type: module
      - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
        type: module
      - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
        type: module
      - url: /hacsfiles/lovelace-auto-entities/auto-entities.js 
        type: module
        
logger:
  default: info
  
# Text to speech
tts:
  - platform: google_translate

# Вынос во внешние файлы
timer: !include includes/timer.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
vacuum: !include includes/vacuum.yaml
fan: !include includes/fan.yaml
remote: !include includes/remote.yaml
media_player: !include includes/media_player.yaml


# Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
switch: !include_dir_merge_list includes/switches
script: !include_dir_merge_named includes/scripts
binary_sensor: !include_dir_merge_list includes/bin_sensor
input_select: !include_dir_merge_named   includes/input_select
input_number: !include_dir_merge_named   includes/input_numbers

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 192.168.1.107
  
  
influxdb:
  api_version: 1 
  max_retries: 5
  default_measurement: state
  host: !secret influxdb_host
  port: !secret influxdb_port
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: !secret influxdb_database
  component_config:
    sensor.xiaomi_airpurifier_air_quality_pm25:
      override_measurement: aqi
    sensor.omv_sdc:
      override_measurement: drive
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature
    sensor.*battery*:
      override_measurement: battery
    sensor.*power*:
      override_measurement: energy
    sensor.*consumption*:
      override_measurement: energy
  tags_attributes:
    - room
    - type
    - friendly_name

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret tg_valaz_id

notify:
  - name: tg_valaz
    platform: telegram
    chat_id: !secret tg_valaz_id
    
pi_hole:
  host: 192.168.1.115
  api_key: !secret pi_hole_api_key
    
    
    