title: Home Assistant - сервер

swipe_nav:
  wrap: false
  animate: swipe
  prevent_default: true
  swipe_amount: 30

views:

  - title: Главная
    icon: mdi:home-assistant
    cards: !include includes/views/common_cards.yaml

  - title: Климат
    icon: mdi:home-thermometer
    cards: !include includes/views/climate_cards.yaml

  - title: Дом
    icon: mdi:home
    cards: !include includes/views/rooms_cards.yaml

  - title: Devices
    icon: mdi:sitemap
    cards: !include includes/views/devices_cards.yaml

  - title: Zigbee
    icon: mdi:zigbee
    cards: !include includes/views/zigbee_cards.yaml
