title: Home Assistant - сервер

swipe_nav:
  wrap: false
  animate: swipe
  prevent_default: true
  swipe_amount: 30

views:

  - title: Главная
    icon: mdi:home-assistant
    
    # cards:
    #   - type: horizontal-stack
    cards:
    
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.home_assistant 
          - type: markdown
            content: >
             **Текущее состояние**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.last_boot_custom
            - entity: sensor.online_custom
            - entity: sensor.time
              name: Текущее время
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-check-outline
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.maria_db_size
              name: Объем БД
              icon: mdi:database
       #=============================
      #=== Component Counts
      #=============================
          - type: glance
            title: 'Количество компонентов'
            columns: 4
            entities:
              - entity: sensor.count_automations
                name: Automations
                icon: mdi:autorenew
              - entity: sensor.count_scripts
                name: Scripts
                icon: mdi:script-text-outline
              - entity: sensor.count_zones
                name: Zones
                icon: mdi:map-marker-radius
              - entity: sensor.count_device_trackers
                name: Device Trackers
                icon: mdi:map-marker
              - entity: sensor.count_switches
                name: Switches
                icon: mdi:light-switch
              - entity: sensor.count_sensors
                name: Sensors
                icon: mdi:resistor
              - entity: sensor.count_binary_sensors
                name: Binary Sensors
                icon: mdi:unfold-more-horizontal
              - entity: sensor.count_input_booleans
                name: Input Booleans
                icon: mdi:toggle-switch
              - entity: sensor.count_input_numbers
                name: Input Numbers
                icon: mdi:numeric
              - entity: sensor.count_input_texts
                name: Input Texts
                icon: mdi:alphabetical
              - entity: sensor.count_input_selects
                name: Input Select
                icon: mdi:view-list
              - entity: sensor.count_input_datetimes
                name: Input Date Times
                icon: mdi:calendar-clock
    
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
             **Графики** 
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Загрузка CPU
                unit: '%'
                entity: sensor.processor_use_percent
                severity:
                    green: 0
                    yellow: 60
                    red: 85
              - type: gauge
                name: Загрузка ОЗУ
                unit: '%'
                entity: sensor.memory_use_percent
                severity:
                    green: 0
                    yellow: 60
                    red: 85
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Диск заполнен
                unit: '%'
                entity: sensor.disk_use_percent
                severity:
                    green: 0
                    yellow: 60
                    red: 85
              - type: gauge
                name: Свободное место
                unit: 'Гб'
                entity: sensor.disk_free
                severity:
                    red: 2
                    yellow: 6
                    green: 8
          - type: history-graph
            entities:
              - entity: sensor.maria_db_size
                name: Maria DB

  - title: Климат
    icon: mdi:home-thermometer
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
             **Температура**
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Гостиная
                entities:
                  - sensor.xiaomi_airpurifier_temperature
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
              - type: custom:mini-graph-card
                name: Кухня
                entities:
                  - sensor.e72e01500c8f_temperature
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
              - type: custom:mini-graph-card
                name: Лоджия
                entities:
                  - sensor.0x158d0005800735_temperature
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Спальня
                entities:
                  - sensor.rm4_mini_temperature
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
              - type: custom:mini-graph-card
                name: Детская
                entities:
                  - sensor.0x158d000586695c_temperature
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
                
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
             **Влажность**
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Гостиная
                entities:
                  - sensor.xiaomi_airpurifier_humidity
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
              - type: custom:mini-graph-card
                name: Кухня
                entities:
                  - sensor.e72e01500c8f_humidity
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
              - type: custom:mini-graph-card
                name: Лоджия
                entities:
                  - sensor.0x158d0005800735_humidity
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Спальня
                entities:
                  - sensor.rm4_mini_humidity
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
              - type: custom:mini-graph-card
                name: Детская
                entities:
                  - sensor.0x158d000586695c_humidity
                hour24: true
                show:
                  graph: false
                  icon: true
                  extrema: true
                  fill: false
                align_state: center
            
          - type: custom:mini-graph-card
            name: Уровень PM2.5
            entities:
              - sensor.xiaomi_airpurifier_air_quality_pm25
            hour24: true
            show:
              graph: true
              icon: true
              extrema: true
              fill: true
            align_state: center
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.xiaomi_airpurifier_air_quality_pm25
              - entity: fan.xiaomi_miio_device
              - entity: input_select.xiaomi_airpurifier_mode
              - entity: input_number.xiaomi_airpurifier_favorite_level
              - entity: switch.xiaomi_airpurifier_child_lock
              - entity: switch.xiaomi_airpurifier_led
              - entity: sensor.xiaomi_airpurifier_speed
              - entity: sensor.xiaomi_airpurifier_filter_remaining
            theme: default
            title: Air Purifier
            
    
                
              
  - title: Дом
    icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
        #   - type: markdown
        #     content: >
        #      **Комнаты**
          - type: custom:vertical-stack-in-card
            title: Гостиная
            cards:
              - type: glance
                show_name: false
                entities:
                  - sensor.xiaomi_airpurifier_temperature
                  - sensor.xiaomi_airpurifier_humidity
                  - sensor.xiaomi_airpurifier_air_quality_pm25
              - type: entities
                entities:
                 - fan.xiaomi_miio_device
                 - media_player.android_tv
          - type: custom:vertical-stack-in-card
            title: Коридор
            cards:
              - type: entities
                entities:
                 - sensor.last_clean_custom
                 - vacuum.roborock_s5
               
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:vertical-stack-in-card
                title: Спальня
                cards:
                  - type: glance
                    show_name: false
                    entities:
                      - sensor.rm4_mini_temperature
                      - sensor.rm4_mini_humidity
              - type: custom:vertical-stack-in-card
                title: Детская
                cards:
                  - type: glance
                    show_name: false
                    entities:
                      - sensor.0x158d000586695c_temperature
                      - sensor.0x158d000586695c_humidity
          - type: horizontal-stack
            cards:
              - type: custom:vertical-stack-in-card
                title: Кухня
                cards:
                  - type: glance
                    show_name: false
                    entities:
                      - sensor.e72e01500c8f_temperature
                      - sensor.e72e01500c8f_humidity
              - type: custom:vertical-stack-in-card
                title: Лоджия
                cards:
                  - type: glance
                    show_name: false
                    entities:
                      - sensor.0x158d0005800735_temperature
                      - sensor.0x158d0005800735_humidity
    
  - title: Devices
    icon: mdi:sitemap
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.xiaomi_airpurifier_air_quality_pm25
              - entity: fan.xiaomi_miio_device
              - entity: input_select.xiaomi_airpurifier_mode
              - entity: input_number.xiaomi_airpurifier_favorite_level
              - entity: switch.xiaomi_airpurifier_child_lock
              - entity: switch.xiaomi_airpurifier_led
              - entity: sensor.xiaomi_airpurifier_speed
              - entity: sensor.xiaomi_airpurifier_filter_remaining
            theme: default
            title: Очиститель воздуха
            
      - type: vertical-stack
        cards:
          - type: 'custom:vacuum-card'
            entity: vacuum.roborock_s5
            stats:
              default:
                - attribute: filter_left
                  unit: hours
                  subtitle: Filter
                - attribute: side_brush_left
                  unit: hours
                  subtitle: Side brush
                - attribute: main_brush_left
                  unit: hours
                  subtitle: Main brush
                - attribute: sensor_dirty_left
                  unit: hours
                  subtitle: Sensors
              cleaning:
                - attribute: cleaned_area
                  unit: m2
                  subtitle: Cleaning area
                - attribute: cleaning_time
                  unit: minutes
                  subtitle: Cleaning time
            actions:
              - name: Clean living room
                service: script.clean_living_room
                icon: 'mdi:sofa'
              - name: Clean bedroom
                service: script.clean_bedroom
                icon: 'mdi:bed-empty'
              - name: Clean kitchen
                service: script.clean_kitchen
                icon: 'mdi:silverware-fork-knife'
            
  - title: Zigbee
    icon: mdi:zigbee
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: 'Уровень заряда'
            show_header_toggle: false
            entities:          
              - entity: sensor.0x158d000586695c_battery
              - entity: sensor.0x158d0005800735_battery
              - entity: sensor.e72e01500c8f_battery
          
          
          
          
          