title: Home Assistant - сервер

swipe_nav:
  wrap: false
  animate: swipe
  prevent_default: true
  swipe_amount: 30

views:
  - !include lovelace/01_system.yaml
  - !include lovelace/02_rooms.yaml
  - !include lovelace/03_climate.yaml
  - !include lovelace/04_devices.yaml
  - !include lovelace/05_homelab.yaml
  - !include lovelace/06_zigbee.yaml
  